title: "Roots Power - Expert Electrical Solutions"
description: "Professional electrical services for residential and commercial projects in Eureka, CA. Licensed contractor with 20+ years experience. Emergency services available."
url: "https://roots-power.vercel.app"
phone: "(707) 441-9436"
email: "rj@rootspower.com"
license: "CSLB Lic.# 901433"

address:
  street: "1453 Gibson Dr."
  city: "Eureka"
  state: "CA"
  zip: "95503"

social:
  facebook: ""
  instagram: ""
  linkedin: ""
  twitter: ""
