name: Auto-Update Registry

on:
  push:
    branches: [main]
    paths:
      - "_data/services/**"
      - "_data/projects/**"
  workflow_dispatch:

jobs:
  update-registry:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Update registries
        run: |
          node update-registry.js

      - name: Check for changes
        id: verify-changed-files
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.verify-changed-files.outputs.changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add _data/services-registry.yml _data/projects-registry.yml
          git commit -m "🤖 Auto-update registries after CMS changes"
          git push
